name: 'Test AWS Access'

# The workflow should only trigger on manual events or pull requests to the main branch
on:
  pull_request:
    branches:
      - main

# Required to get the ID Token that will be used for OIDC
permissions:
  id-token: write
  contents: read

jobs:
  aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-east-1
          role-to-assume: arn:aws:iam::362356772159:role/sts-lab-2-target
          role-session-name: OIDCSession

      - run: aws secretsmanager get-secret-value --secret-id flag_sts_lab_2
        shell: bash
